version: "1.0"
data_path: "LON"
batch_size: 32
num_workers: 0
top_p: 0.3
hidden_size: 128
learning_rate: 1e-3
special_tokens:
    - "[CON]"
    - "[QUE]"
    - "[ANS]"
    - "[DIS]"
gpus: 1
max_epochs: 10
check_val_every_n_epoch: 1
fast_dev_run: 1
