data_path: "LON"
num_workers: 0
batch_size: 2
version: 8.8
pretrained_model: "t5-small"
auto_lr_find: False
terminate_on_nan: True
benchmark: True
track_grad_norm: 2
precision: 16
accumulate_grad_batches: 10
gradient_clip_val: 5
stochastic_weight_avg: True
enable_pl_optimizer: True
learning_rate: 1e-05
special_tokens:
    - "[CON]"
    - "[QUE]"
    - "[ANS]"
    - "[DIS]"
gpus: 1
max_epochs: 1
log_every_n_steps: 150
check_val_every_n_epoch: 1
