data_path: "data/RACE_processed"
d_model: 128
nhead: 8
batch_size: 1
num_workers: 0
num_layers: 1
top_p: 0.5
learning_rate: 1e-05
special_tokens:
    - "[CON]"
    - "[QUE]"
    - "[ANS]"
    - "[DIS]"
pretrained_model: "prajjwal1/bert-tiny"
gpus: 1
max_epochs: 1
check_val_every_n_epoch: 1
